const VISIBILITY_FILTER_SHOW_ALL = 'SHOW_ALL'
const VISIBILITY_FILTER_SHOW_COMPLETED = 'SHOW_COMPLETED'
const VISIBILITY_SHOW_ACTIVE = 'SHOW_ACTIVE'

export {
  VISIBILITY_FILTER_SHOW_ALL,
  VISIBILITY_FILTER_SHOW_COMPLETED,
  VISIBILITY_SHOW_ACTIVE,
}